#!/bin/bash
sudo timedatectl set-timezone 'Asia/Kolkata'      # To set the time zone to ‘Asia/Kolkata’
sudo timedatectl set-ntp yes                      # Synchronizing the system clock with a remote server using NTP
